# Generated by Django 3.2.3 on 2021-05-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210523_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='userfile',
            field=models.FileField(null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='blog.Category'),
        ),
    ]
